In [1]:
import numpy as np

In [9]:
#Array creation

a= np.array(10)
a
type(a
    )

numpy.ndarray

In [10]:
#Zero dimensional array

In [12]:
z=np.array(10)
z.ndim

0

In [13]:
#One dimensional array

In [14]:
o=np.array([10,12,12,15])
o.ndim
            

1

In [15]:
#Two dimensional array

In [16]:
t=np.array([[10,12,14,15,16]])

In [17]:
t.ndim

2

In [18]:
#Three dimensional array

In [19]:
th= np.array([[[10,12,14,15,16]]])

In [20]:
th.ndim

3

In [21]:
#Change the data type of array elements.

In [22]:
a=np.array([10,15,52,54])

In [23]:
a.dtype

dtype('int64')

In [25]:
a=np.array([10,15,52,54], dtype= float)
print(a.dtype)
a

float64


array([10., 15., 52., 54.])

# Other ways of creating an array

1. arange
2. linspace
3. zeros
4. ones
5. random

In [28]:
a=np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
b=np.linspace(1,5,15, retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [35]:
z= np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [37]:
o=np.ones([3,3])
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
r= np.random.rand(5,5)

In [40]:
r

array([[0.84927789, 0.6461996 , 0.31341854, 0.07735216, 0.72388678],
       [0.67150594, 0.99400833, 0.70231171, 0.08003665, 0.40317585],
       [0.90068124, 0.03251726, 0.86469633, 0.06847077, 0.18964058],
       [0.90550683, 0.53875192, 0.78841313, 0.65161426, 0.28839022],
       [0.61866892, 0.94627673, 0.92778581, 0.62982699, 0.96566054]])

In [41]:
r=np.random.randint(5, size=10)

In [42]:
r

array([3, 1, 0, 2, 4, 0, 4, 0, 3, 0])

# Slicing and Indexing of arrays

In [43]:
a=np.array([[1,2,3],[4,5,6]])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a[0,0]

1

In [46]:
a[0,1]

2

In [47]:
a[1,1]

5

In [48]:
a[1,2]

6

In [50]:
a[0,1:]

array([2, 3])

In [52]:
a[1:,0:]

array([[4, 5, 6]])

In [53]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [60]:
#3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays


In [61]:
a=np.random.rand(5,2)

In [62]:
a

array([[0.05810274, 0.09905351],
       [0.52816841, 0.35136875],
       [0.40173328, 0.66473648],
       [0.96547631, 0.35347739],
       [0.79806688, 0.56060526]])

In [63]:
a.reshape(2,5)

array([[0.05810274, 0.09905351, 0.52816841, 0.35136875, 0.40173328],
       [0.66473648, 0.96547631, 0.35347739, 0.79806688, 0.56060526]])

In [64]:
a.reshape(10,1)

array([[0.05810274],
       [0.09905351],
       [0.52816841],
       [0.35136875],
       [0.40173328],
       [0.66473648],
       [0.96547631],
       [0.35347739],
       [0.79806688],
       [0.56060526]])

In [65]:
a.reshape(5,2)

array([[0.05810274, 0.09905351],
       [0.52816841, 0.35136875],
       [0.40173328, 0.66473648],
       [0.96547631, 0.35347739],
       [0.79806688, 0.56060526]])

In [70]:
a.reshape(1,10)
a

array([[0.05810274, 0.09905351],
       [0.52816841, 0.35136875],
       [0.40173328, 0.66473648],
       [0.96547631, 0.35347739],
       [0.79806688, 0.56060526]])

In [71]:
a.reshape(5,-1)
a

array([[0.05810274, 0.09905351],
       [0.52816841, 0.35136875],
       [0.40173328, 0.66473648],
       [0.96547631, 0.35347739],
       [0.79806688, 0.56060526]])

# Aggregate functions
* The Python numpy aggregate functions are sum, min, mean,average,product,nedian,standard deviation,variance,percentile and corrcoef.

In [72]:
a.min()

0.05810273618322137

In [73]:
a.std()

0.27231581562587714

In [74]:
a.mean()

0.47807890077960397

In [75]:
a.var()

0.07415590343998671

# Stacking 
Stacking is used ot join two different arrays
* Vertical stacking
* Horizontal stacking

In [76]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [77]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [78]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])